version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: quarterly

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: monthly
