---
upstream:
  domain: lyrica-main-2.herokuapp.com
  port: 443
  ssl: true
  base_url: /
app_id: com.Rnova.lyrica
res:
  song_lib: res/sheet/SongLibSheet.asset
  language: res/sheet/LanguageSheet.asset
  singer: res/sheet/SingerSheet.asset
  songlyrics: res/songlyrics/SongLyrics%02d.txt
  songlyrics_b: res/songlyrics/SongLyrics%02dB.txt
